# Generated by Django 2.2.1 on 2019-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='showLat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='showLong',
            field=models.FloatField(null=True),
        ),
    ]
